version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres-db
      - cache
    env_file:
      - .env

  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  cache:
    image: redis:6
    env_file:
      - .env
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"

volumes:
  postgres_data:
